name: 'Build'

on:
  pull_request:
  push: # Do not rely on `push` for PR CI - see https://github.com/guardian/mobile-apps-api/pull/2760
    branches:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write # Required for riff-raff action

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: corepack enable

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - name: Setup sbt
        uses: sbt/setup-sbt@v1
        with:
          disk-cache: false

      - name: Compile
        run: sbt Test/compile

      - name: Test/definedTestDigests
        run: sbt show Test/definedTestDigests
